In [1]:
# K-Nearest Neighbors (K-NN)
# Importing the libraries

import pandas as pd
import numpy as np
from sklearn import metrics, preprocessing, linear_model

In [2]:
# Importing the dataset

training_data = pd.read_csv('~/desktop/training_data.csv', header=0)
prediction_data = pd.read_csv('~/desktop/tournament_data.csv', header=0)

#dataset = pd.read_csv('Social_Network_Ads.csv')
#X = dataset.iloc[:, [2, 3]].values
#y = dataset.iloc[:, 4].values

# Transform the loaded CSV data into numpy arrays
Y = training_data['target']
X = training_data.drop('target', axis=1)
t_id = prediction_data['t_id']
x_prediction = prediction_data.drop('t_id', axis=1)

In [3]:
training_data.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature42,feature43,feature44,feature45,feature46,feature47,feature48,feature49,feature50,target
0,0.523989,0.450736,0.642132,0.283390,0.489685,0.365986,0.750027,0.441617,0.705939,0.298719,...,0.560302,0.568412,0.796156,0.298466,0.537179,0.394989,0.278652,0.366975,0.624429,1
1,0.361765,0.356233,0.695955,0.525630,0.710569,0.256446,0.597307,0.346839,0.460739,0.642520,...,0.351684,0.418981,0.469897,0.477661,0.392151,0.323126,0.695662,0.483652,0.472957,1
2,0.539965,0.515231,0.648920,0.351373,0.397574,0.583674,0.590925,0.593623,0.549570,0.200306,...,0.644756,0.641817,0.607814,0.365455,0.416702,0.353930,0.406990,0.486172,0.314644,0
3,0.443803,0.660315,0.193312,0.703555,0.331931,0.475221,0.472761,0.422789,0.499109,0.691708,...,0.662121,0.308120,0.621211,0.506328,0.455108,0.551172,0.142444,0.531190,0.632066,1
4,0.527979,0.671884,0.626454,0.519041,0.489633,0.422479,0.379481,0.649083,0.300018,0.584167,...,0.433420,0.349900,0.512786,0.369433,0.299567,0.426600,0.500205,0.647980,0.465402,0

In [4]:
prediction_data.head()

,t_id,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature41,feature42,feature43,feature44,feature45,feature46,feature47,feature48,feature49,feature50
0,63770,0.681806,0.457087,0.516664,0.607804,0.729960,0.415469,0.427211,0.514822,0.560296,...,0.258327,0.382377,0.308288,0.449678,0.635480,0.646590,0.726018,0.743960,0.517911,0.668009
1,78049,0.355205,0.422402,0.375170,0.696944,0.541327,0.486012,0.486265,0.456990,0.448401,...,0.368480,0.568183,0.386535,0.412783,0.606591,0.393434,0.586397,0.579987,0.381867,0.497290
2,41745,0.465689,0.329402,0.474439,0.427206,0.461227,0.522397,0.533084,0.487378,0.553240,...,0.340825,0.562935,0.625544,0.467350,0.630630,0.560783,0.562955,0.612297,0.443976,0.522527
3,49386,0.455315,0.447960,0.383916,0.468395,0.512756,0.635306,0.613820,0.307091,0.574680,...,0.316860,0.748022,0.637350,0.338557,0.926226,0.645144,0.483734,0.509731,0.420474,0.413482
4,28187,0.379705,0.425805,0.539373,0.442157,0.568863,0.569497,0.750688,0.435134,0.674608,...,0.631482,0.477551,0.555333,0.463540,0.431556,0.480638,0.344906,0.313420,0.211184,0.448168

In [5]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
x_prediction = sc.transform(x_prediction)

In [6]:
# Transform the loaded CSV data into numpy arrays
Y = training_data['target']
X = training_data.drop('target', axis=1)
t_id = prediction_data['t_id']
x_prediction = prediction_data.drop('t_id', axis=1)

In [7]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', max_depth=2, random_state = 0)
classifier.fit(X, Y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=50,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [8]:
# Predicting the Test set results
y_prediction = classifier.predict_proba(x_prediction)
print (y_prediction)

[[ 1.          0.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 ...,
 [ 0.45539906  0.54460094]
 [ 1.          0.        ]
 [ 1.          0.        ]]

In [9]:
results = y_prediction[:, 1]
results_df = pd.DataFrame(data={'probability':results})
joined = pd.DataFrame(t_id).join(results_df)
joined.head()

    t_id  probability
0  63770          0.0
1  78049          1.0
2  41745          1.0
3  49386          1.0
4  28187          1.0

In [10]:
joined.to_csv("Decisionâ€“Treeâ€“2â€“predictions.csv", index=False)